# Generated by Django 6.0 on 2025-12-13 09:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_customuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.RegexValidator('^998\\d{9}$', message="Phone number must be entered in the format: '998123456789'. Up to 15 digits allowed.")]),
        ),
    ]
